version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  build:
    docker:
      - image: circleci/python:2.7-node
    environment:
      AWS_REGION: us-east-1
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - aws-s3/sync:
          from: build
          to: "s3://ci-cd-pipeline11/"
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          overwrite: true
  test:
    docker:
      - image: circleci/python:2.7-node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
